volumes:
  gnoland-vol: {}
  grafana-vol: {}

networks:
  gnoland-net:
    driver: bridge
  dash-net:
    driver: bridge

secrets:
  grafana-sec:
    file: ./grafana/grafana.ini

services:
  gnoland:
    image: sw360cab/aib-gnoland
    restart: unless-stopped
    command:
      - gnoland
      - start
      - --skip-failing-genesis-txs
      - --log-level=info
    volumes:
      - gnoland-vol:/opt/gno/src/gno.land/gnoland-data
    networks:
      - gnoland-net
    # ports:
    #   - 36657:36657
    #   - 26657:26657

  gnoweb:
    image: sw360cab/aib-gnoland
    command:
      - gnoweb
      - --bind=0.0.0.0:8088
      - --remote=gnoland:26657
    networks:
      - gnoland-net
    ports:
      - 8088:8088

  tx-indexer:
    image: sw360cab/aib-tx-indexer
    restart: unless-stopped
    # command: start --remote http://test3.gno.land:36657 --db-path indexer-db --listen-address 0.0.0.0:8546
    command: start --remote http://gnoland:26657 --db-path indexer-db --listen-address 0.0.0.0:8546
    networks:
      - gnoland-net
 
  supernova:
    image: sw360cab/aib-supernova
    command: >
      -sub-accounts 5 -transactions 1000 -url http://gnoland:26657
      -mnemonic "source bonus chronic canvas draft south burst lottery vacant surface solve popular case indicate oppose farm nothing bullet exhibit title speed wink action roast"
    networks:
      - gnoland-net

  houston:
    build: houston/
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - GRAPHQL_URL=http://tx-indexer:8546/graphql/query
    networks:
      - gnoland-net
      - dash-net

  grafana:
    image: grafana/grafana:10.4.2
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana-sec
    secrets:
      - grafana-sec
    volumes:
      - grafana-vol:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - dash-net
    ports:
     - '3000:3000'
