volumes:
  gnoland-vol: {}
  grafana-vol: {}

networks:
  gnoland-net:
  dash-net:

secrets:
  grafana-sec:
    file: ./grafana/grafana.ini

services:
  gnoland:
    build:
      context: gno/
      dockerfile: Dockerfile
    command:
      - gnoland
      - start
      - --skip-failing-genesis-txs
      - --log-level=info
    volumes:
      - gnoland-vol:/opt/gno/src/gno.land/gnoland-data
    networks:
      - gnoland-net
    # ports:
    #   - 36657:36657
    #   - 26657:26657

  gnoweb:
    build:
      context: gno/
      dockerfile: Dockerfile
    command:
      - gnoweb
      - --bind=0.0.0.0:8088
      - --remote=gnoland:26657
    networks:
      - gnoland-net
      - dash-net
    ports:
      - 8088:8088

  tx-indexer:
    build:
      context: tx-indexer/
    # command: start --remote http://test3.gno.land:36657 --db-path indexer-db --listen-address 0.0.0.0:8546
    command: start --remote http://gnoland:26657 --db-path indexer-db --listen-address 0.0.0.0:8546
    # Publish port to test GraphQL server
    networks:
      - gnoland-net
    ports:
      - 8546:8546

  supernova:
    build:
      context: supernova/
      dockerfile: ../supernova.Dockerfile
    command: >
      -sub-accounts 5 -transactions 1000 -url http://gnoland:26657
      -mnemonic "source bonus chronic canvas draft south burst lottery vacant surface solve popular case indicate oppose farm nothing bullet exhibit title speed wink action roast"
    networks:
      - gnoland-net

  houston:
    build: houston/
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - GRAPHQL_URL=http://tx-indexer:8546/graphql/query
    networks:
      - gnoland-net
      - dash-net
    # Publish port to test purposes
    ports:
     - '8080:8080'

  grafana:
    image: grafana/grafana:latest # 10.4.2
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    networks:
      - dash-net
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
     - '3001:3000'

  grafana2:
    image: grafana/grafana:10.4.2
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      # - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana-sec
    secrets:
      - grafana-sec
    volumes:
      - grafana-vol:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - dash-net
    ports:
     - '3000:3000'
