services:
  gnoland:
    command: --config-path /opt/gno/src/gno.land/config/config.toml
    volumes:
      - gnoland-vol:/opt/gno/src/gno.land/gnoland-data
      - ./gnoland/config.toml:/opt/gno/src/gno.land/config/config.toml
    ports:
      - 36657:36657
      - 26657:26657


  tx-indexer:
    command: --log-level debug
    # Publish port to test GraphQL server
    ports:
      - 8546:8546

  houston:
    environment:
      - GRAPHQL_URL=http://tx-indexer:8546/graphql/query
      - GIN_MODE=release
      - LOG_LEVEL=debug
    # Publish port for test purposes
    ports:
     - '8080:8080'