volumes:
  gnoland-vol: {}
  indexer-vol: {}
  grafana-vol: {}

networks:
  gnoland-net:
    driver: bridge
  dash-net:
    driver: bridge

secrets:
  grafana-sec:
    file: ./grafana/grafana.ini

services:
  gnoland:
    image: sw360cab/aib-gnoland
    restart: unless-stopped
    entrypoint:
      - gnoland
      - start
      - --skip-failing-genesis-txs
      - --log-level=info
    volumes:
      - gnoland-vol:/opt/gno/src/gno.land/gnoland-data
    networks:
      - gnoland-net

  gnoweb:
    image: sw360cab/aib-gnoland
    entrypoint:
      - gnoweb
      - --bind=0.0.0.0:8088
      - --remote=gnoland:26657
    networks:
      - gnoland-net
    ports:
      - 8088:8088

  tx-indexer:
    image: sw360cab/aib-tx-indexer
    restart: unless-stopped
    # entrypoint: /usr/local/bin/indexer start --remote http://test3.gno.land:36657 --db-path /opt/indexer-db --listen-address 0.0.0.0:8546
    entrypoint: /usr/local/bin/indexer start --remote http://gnoland:26657 --db-path /opt/indexer-db --listen-address 0.0.0.0:8546
    networks:
      - gnoland-net
    volumes:
      - indexer-vol:/opt/indexer-db
 
  supernova:
    image: sw360cab/aib-supernova
    command: >
      -sub-accounts 10 -transactions 100 -url http://gnoland:26657 -mode REALM_CALL
      -mnemonic "source bonus chronic canvas draft south burst lottery vacant surface solve popular case indicate oppose farm nothing bullet exhibit title speed wink action roast"
    networks:
      - gnoland-net

  houston:
    build: houston/
    restart: unless-stopped
    environment:
      - GRAPHQL_URL=http://tx-indexer:8546/graphql/query
      - GIN_MODE=release
      - LOG_LEVEL=info
    networks:
      - gnoland-net
      - dash-net

  grafana:
    image: grafana/grafana:10.4.2
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana-sec
    secrets:
      - grafana-sec
    volumes:
      - grafana-vol:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - dash-net
    ports:
     - 3000:3000
