apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-indexer
  template:
    metadata:
      labels:
        app: tx-indexer
    spec:
      containers:
      - name: tx-indexer
        image: sw360cab/aib-tx-indexer
        imagePullPolicy: IfNotPresent
        args: ["start", "--remote", "http://gnoland:26657", "--db-path", "/opt/indexer-db", "--listen-address", "0.0.0.0:8546"]
        volumeMounts:
        - name: indexer-vol
          mountPath: /opt/indexer-db
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        ports:
          - containerPort: 8546
      volumes:
      - name: indexer-vol
        persistentVolumeClaim:
          claimName: indexer-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: tx-indexer
spec:
  selector:
    app: tx-indexer
  ports:
  - port: 8546
    targetPort: 8546
    protocol: TCP
